CREATE TABLE business_objects (
    business_object_id VARCHAR(100) NOT NULL,
    name_fr_lbl VARCHAR(100) NOT NULL,
    name_en_lbl VARCHAR(100) NOT NULL,
    description_fr_lbl TEXT NULL,
    description_en_lbl TEXT NULL,
    is_deleted_flg TINYINT(1) NOT NULL DEFAULT 0,
    hotfix_eligibility_flg TINYINT(1) NOT NULL DEFAULT 0,
    is_updatable_flg TINYINT(1) NOT NULL DEFAULT 1,
    source_cod VARCHAR(20) NOT NULL DEFAULT 'IMPORT',
    audit_creation_user_login_id VARCHAR(100) NULL,
    audit_creation_time DATETIME NULL,
    audit_update_user_login_id VARCHAR(100) NULL,
    audit_update_time DATETIME NULL,
    audit_update_roles_typ VARCHAR(200) NULL,
    audit_update_application_iua_cod VARCHAR(5) NULL,
    auditFile_file_id INT NULL,
    auditFile_filename_txt VARCHAR(200) NULL,
    auditFile_file_typ VARCHAR(100) NULL,
    auditFile_control_id VARCHAR(100) NULL,
    auditFile_creation_user_login_id VARCHAR(100) NULL,
    auditFile_file_dat DATETIME NULL,
    auditFile_row_nbr BIGINT NULL,
    CONSTRAINT PK_business_objects PRIMARY KEY (business_object_id)
);

CREATE TABLE functional_controls (
    functional_control_id VARCHAR(200) NOT NULL,
    subfamily_id VARCHAR(100) NULL,
    functional_control_en_lbl VARCHAR(100) NOT NULL,
    functional_control_fr_lbl VARCHAR(100) NOT NULL,
    description_en_txt TEXT NULL,
    description_fr_txt TEXT NULL,
    criticity_typ VARCHAR(20) NULL,
    designer_login_id VARCHAR(100) NULL,
    responsible_login_id VARCHAR(100) NULL,
    frequency_typ VARCHAR(1) NULL,
    is_deleted_flg TINYINT(1) NOT NULL DEFAULT 0,
    is_visible_flg TINYINT(1) NOT NULL DEFAULT 1,
    audit_creation_user_login_id VARCHAR(100) NULL,
    audit_creation_time DATETIME NULL,
    audit_update_user_login_id VARCHAR(100) NULL,
    audit_update_time DATETIME NULL,
    audit_update_roles_typ VARCHAR(200) NULL,
    audit_update_application_iua_cod VARCHAR(5) NULL,
    auditFile_file_id INT NULL,
    auditFile_filename_txt VARCHAR(200) NULL,
    auditFile_file_typ VARCHAR(100) NULL,
    auditFile_creation_user_login_id VARCHAR(100) NULL,
    auditFile_file_dat DATETIME NULL,
    auditFile_row_nbr BIGINT NULL,
    CONSTRAINT PK_functional_controls PRIMARY KEY (functional_control_id)
);

CREATE TABLE business_object_fields (
    business_object_field_id VARCHAR(101) NOT NULL,
    business_object_id VARCHAR(100) NOT NULL,
    golden_source_iua_cod VARCHAR(3) NULL,
    field_cod VARCHAR(50) NOT NULL,
    data_typ VARCHAR(30) NOT NULL,
    field_typ VARCHAR(20) NOT NULL,
    name_fr_lbl VARCHAR(100) NOT NULL,
    name_en_lbl VARCHAR(100) NOT NULL,
    description_fr_lbl TEXT NULL,
    description_en_lbl TEXT NULL,
    nature_field_typ VARCHAR(200) NULL DEFAULT 'DATA',
    is_mandatory_flg TINYINT(1) NULL DEFAULT 0,
    is_deleted_flg TINYINT(1) NOT NULL DEFAULT 0,
    hotfix_eligibility_flg TINYINT(1) NOT NULL DEFAULT 0,
    is_updatable_flg TINYINT(1) NOT NULL DEFAULT 1,
    source_cod VARCHAR(20) NOT NULL DEFAULT 'IMPORT',
    audit_creation_user_login_id VARCHAR(100) NULL,
    audit_creation_time DATETIME NULL,
    audit_update_user_login_id VARCHAR(100) NULL,
    audit_update_time DATETIME NULL,
    audit_update_roles_typ VARCHAR(200) NULL,
    audit_update_application_iua_cod VARCHAR(5) NULL,
    auditFile_file_id INT NULL,
    auditFile_filename_txt VARCHAR(200) NULL,
    auditFile_file_typ VARCHAR(100) NULL,
    auditFile_creation_user_login_id VARCHAR(100) NULL,
    auditFile_file_dat DATETIME NULL,
    auditFile_row_nbr BIGINT NULL,
    CONSTRAINT PK_business_object_fields PRIMARY KEY (business_object_field_id),
    CONSTRAINT FK_bof_bo FOREIGN KEY (business_object_id) REFERENCES business_objects(business_object_id)
);

CREATE TABLE typologies (
    typology_id VARCHAR(200) NOT NULL,
    control_id VARCHAR(50) NOT NULL, 
    typology_cod VARCHAR(149) NOT NULL,
    typology_fr_lbl VARCHAR(250) NULL,
    typology_en_lbl VARCHAR(250) NULL,
    business_object_id VARCHAR(100) NULL,
    business_object_field_id VARCHAR(101) NULL,
    remediation_flg TINYINT(1) NOT NULL DEFAULT 0,
    pre_analysis_flg TINYINT(1) NOT NULL DEFAULT 0,
    functional_control_id VARCHAR(200) NULL,
    is_deleted_flg TINYINT(1) NOT NULL DEFAULT 0,
    is_visible_flg TINYINT(1) NOT NULL DEFAULT 1,
    creation_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    audit_creation_user_login_id VARCHAR(100) NULL,
    audit_creation_time DATETIME NULL,
    audit_update_time DATETIME NULL,
    audit_update_user_login_id VARCHAR(100) NULL,
    audit_update_roles_typ VARCHAR(200) NULL,
    audit_update_application_iua_cod VARCHAR(5) NULL,
    auditFile_file_id INT NULL,
    auditFile_filename_txt VARCHAR(200) NULL,
    auditFile_file_typ VARCHAR(100) NULL,
    auditFile_creation_user_login_id VARCHAR(100) NULL,
    auditFile_file_dat DATETIME NULL,
    auditFile_row_nbr BIGINT NULL,
    CONSTRAINT PK_typologies PRIMARY KEY (typology_id),
    CONSTRAINT FK_typologies_bo FOREIGN KEY (business_object_id) REFERENCES business_objects(business_object_id),
    CONSTRAINT FK_typologies_fc FOREIGN KEY (functional_control_id) REFERENCES functional_controls(functional_control_id)
);

CREATE TABLE anomalies (
    anomaly_kuid VARCHAR(12) NOT NULL,
    title_txt VARCHAR(200) NULL,
    description_txt TEXT NULL,
    business_object_typ VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
    source_application_iua_cod VARCHAR(3) NOT NULL DEFAULT 'UNK',
    source_functional_anomaly_id TEXT NULL,
    control_id VARCHAR(50) NOT NULL,
    typology_id VARCHAR(200) NOT NULL,
    detection_time DATETIME NULL,
    asof_dat DATE NOT NULL,
    frequency_typ VARCHAR(1) NOT NULL DEFAULT 'D',
    priority_typ VARCHAR(40) NULL,
    hotfix_flg TINYINT(1) NULL DEFAULT 0,
    hotfix_starting_asof_dat DATE NULL,
    hotfix_expiration_asof_dat DATE NULL,
    source_event_typ VARCHAR(100) NULL,
    object_identification_fields TEXT NOT NULL, 
    error_fields TEXT NOT NULL, 
    other_fields TEXT NULL, 
    creation_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    correction_mode_typ VARCHAR(6) NULL,
    CONSTRAINT PK_anomalies PRIMARY KEY (anomaly_kuid)
);

CREATE TABLE generic_anomalies (
    anomaly_kuid VARCHAR(12) NOT NULL,
    title_txt VARCHAR(200) NULL,
    description_txt TEXT NULL,
    business_object_typ VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
    source_application_iua_cod VARCHAR(3) NOT NULL DEFAULT 'UNK',
    source_functional_anomaly_id TEXT NULL,
    control_id VARCHAR(50) NOT NULL,
    typology_id VARCHAR(200) NOT NULL,
    detection_time DATETIME NULL,
    asof_dat DATE NOT NULL,
    frequency_typ VARCHAR(1) NOT NULL DEFAULT 'D',
    priority_typ VARCHAR(40) NULL,
    hotfix_flg TINYINT(1) NULL DEFAULT 0,
    hotfix_starting_asof_dat DATE NULL,
    hotfix_expiration_asof_dat DATE NULL,
    source_event_typ VARCHAR(100) NULL,
    object_identification_fields TEXT NOT NULL,
    error_fields TEXT NOT NULL,
    other_fields TEXT NULL,
    creation_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    correction_mode_typ VARCHAR(6) NULL,
    CONSTRAINT PK_generic_anomalies PRIMARY KEY (anomaly_kuid)
);

CREATE TABLE business_data (
    business_data_id VARCHAR(200) NOT NULL,
    business_object_id VARCHAR(100) NULL,
    business_data_en_lbl TEXT NOT NULL,
    business_data_fr_lbl TEXT NOT NULL,
    description_en_txt TEXT NULL,
    description_fr_txt TEXT NULL,
    critical_data_element_flg TINYINT(1) NOT NULL DEFAULT 0,
    data_domain_producer_cod TEXT NULL,
    data_domain_consumer_cod TEXT NULL,
    owner_department_cod TEXT NULL,
    data_quality_manager_department_cod VARCHAR(50) NULL,
    chain_cod VARCHAR(50) NULL,
    golden_source_iua_cod VARCHAR(3) NULL,
    usage_typ VARCHAR(100) NULL,
    business_indicator_flg TINYINT(1) NOT NULL DEFAULT 0,
    source_cod VARCHAR(20) NOT NULL DEFAULT 'IMPORT',
    notification_method_typ VARCHAR(100) NULL,
    hotfix_eligibility_flg TINYINT(1) NOT NULL DEFAULT 0,
    is_deleted_flg TINYINT(1) NOT NULL DEFAULT 0,
    is_updatable_flg TINYINT(1) NOT NULL DEFAULT 1,
    audit_creation_user_login_id VARCHAR(100) NULL,
    audit_creation_time DATETIME NULL,
    audit_update_user_login_id VARCHAR(100) NULL,
    audit_update_time DATETIME NULL,
    audit_update_roles_typ VARCHAR(200) NULL,
    audit_update_application_iua_cod VARCHAR(5) NULL,
    auditFile_file_id INT NULL,
    auditFile_filename_txt VARCHAR(200) NULL,
    auditFile_file_typ VARCHAR(100) NULL,
    auditFile_creation_user_login_id VARCHAR(100) NULL,
    auditFile_file_dat DATETIME NULL,
    auditFile_row_nbr BIGINT NULL,
    CONSTRAINT PK_business_data PRIMARY KEY (business_data_id),
    CONSTRAINT FK_bd_bo FOREIGN KEY (business_object_id) REFERENCES business_objects(business_object_id)
);

CREATE TABLE business_data_field_link (
    business_object_field_id VARCHAR(101) NOT NULL,
    managing_application_iua_cod VARCHAR(3) NOT NULL,
    business_data_id VARCHAR(100) NOT NULL,
    is_deleted_flg TINYINT(1) NOT NULL DEFAULT 0,
    is_updatable_flg TINYINT(1) NOT NULL DEFAULT 1,
    source_cod VARCHAR(20) NOT NULL DEFAULT 'IMPORT',
    audit_creation_user_login_id VARCHAR(100) NULL,
    audit_creation_time DATETIME NULL,
    audit_update_user_login_id VARCHAR(100) NULL,
    audit_update_time DATETIME NULL,
    audit_update_roles_typ VARCHAR(200) NULL,
    audit_update_application_iua_cod VARCHAR(5) NULL,
    auditFile_file_id INT NULL,
    auditFile_filename_txt VARCHAR(200) NULL,
    auditFile_file_typ VARCHAR(100) NULL,
    auditFile_creation_user_login_id VARCHAR(100) NULL,
    auditFile_file_dat DATETIME NULL,
    auditFile_row_nbr BIGINT NULL,
    CONSTRAINT PK_business_data_field_link PRIMARY KEY (business_object_field_id, managing_application_iua_cod),
    CONSTRAINT FK_bdfl_bof FOREIGN KEY (business_object_field_id) REFERENCES business_object_fields(business_object_field_id)
);